### ISSUE TITLE
Usage example missing CSS

### ISSUE THREAD

**Issue by tgochenour** [mpontus/react-modal-hook#1]
When I first implemented this hook using the example given in 'Usage' documentation I didn't see the modal popup interaction like I expected until I realized the div.modal CSS description was not yet defined.  I changed the example to have a div.modal-content and then defined these two CSS classes so now I see the modal centered in the viewport and overlaying the original content.  

```
const [showModal, hideModal] = useModal(() => (
	<div role="dialog" className="modal">
		<div className="modal-content">
		<p>Modal content</p>
		<button onClick={hideModal}>Hide modal</button>
		</div>
	</div>
));
```

```
div.modal  { position: fixed; z-index: 100; left: 0; top: 0; width: 100%; height: 100%; overflow: auto; background-color: rgb(0,0,0); background-color: rgba(0,0,0,0.4);}
div.modal-content  {background-color: #fefefe; margin: 15% auto; padding: 20px; border: 1px solid #888; width: 80%; }
```

**Comment by mpontus** [comment]
This library does not intend to provide any modal UI, though I agree I should make this point clearer.

I updated the readme with a disclaimer, and updated the examples to use [react-modal](https://github.com/reactjs/react-modal) which should provide a functioning UI out of the box.

Appreciate your feedback.
