### ISSUE TITLE
Tips for triggering modal from different places.

### ISSUE THREAD

**Issue by mmmoli** [mpontus/react-modal-hook#10]
Thanks for this lib!

I'm looking for tips. I have a `react-modal-hook` set-up at `app.tsx`, a view with a button that I want to trigger the modal and a `Header.tsx` to do the same.

Can I share the same context around to use the same modal?

**Comment by mpontus** [comment]
Hi, @mmmoli. You should be able to pass `showModal` to both components if you call `useModal` inside `app.tsx`. Is there some other context to this task that complicates this implementation?

**Comment by mmmoli** [comment]
Thanks for getting back.

I was wondering if there was some way to use the context API. i.e. define the `useModal` hook in `app.js` and _hook_ into the context from any other component.

**Comment by mpontus** [comment]
Sure, you can also use Context API to pass callbacks down to different components. This library does not provide any facilities for that, so you'd have to decide how you want to expose this callback yourself. 

Here's one of the ways to do that:

```js
const ModalContext = React.createContext(function noop() {});

function App() {
  const [showModal, hideModal] = useModal(() => (
    <ReactModal isOpen>
      <p>Modal content</p>
      <button onClick={hideModal}>Hide modal</button>
    </ReactModal>
  ));

  return (
    <ModalContext.Provider value={showModal}>
      <Header />
    </ModalContext.Provider>
  );
}

function Header() {
  const showModal = React.useContext(ModalContext);

  return (
    <header>
      <button onClick={showModal}>Show modal</button>
    </header>
  );
}
```

**Comment by mmmoli** [comment]
That's what I was after. 

Perfect. Thanks!
