### ISSUE TITLE
Closing modal on confirmation

### ISSUE THREAD

**Issue by user010110** [mpontus/react-modal-hook#11]
Hey, thanks for the awesome project!

I'm just wondering about closing modal on confirmation (referring to demo: https://codesandbox.io/s/v8qy4w1j77, line 35) `onConfirm={() => deletePerson(id)}`. How does it work since onConfirm does not call `hideConfirmModal`?

**Comment by mpontus** [comment]
Person update modal (`PersonFormContainer`) is defined as part of Person list item component (`PersonContainer`). When list item is removed, modal is removed as well. 

We call `hideModal` automatically as part of `useEffect` teardown logic inside `useModal`. Take a look here: https://github.com/mpontus/react-modal-hook/blob/9fd8a80d5fee11b055ce343f5017e0d08ef3df81/src/useModal.ts#L64

**Comment by user010110** [comment]
Makes total sense, awesome, thanks!
