### ISSUE TITLE
Adjust the `createPortal` approach

### ISSUE THREAD

**Issue by PeterMK85** [mpontus/react-modal-hook#18]
Currently in the repository it's used in a weird way, `container` used to define a `component` but as far as I concern it should expose a `HTMLElement`.

In this case container interfere, because `MUI` exposes the container DOM element under this name.

I would expose on the `Provider` level, to be able define the root DOM element, thru the `react-modal-hook`'s context.

https://github.com/mpontus/react-modal-hook/blob/master/src/ModalContext.ts#L15
https://github.com/mpontus/react-modal-hook/blob/master/src/ModalRoot.tsx#L64

MUI container definition:
https://material-ui.com/api/popper/#props

**Comment by denieler** [comment]
yeah! we have exactly the same issue in our project 👍 it would be much more logical to expose it on Provider level. Will be glad if it's going to be fixed 🎉

**Comment by havenchyk** [comment]
Hey @mpontus could you please take a look?

**Comment by mpontus** [comment]
Sorry about the delay. I was aware of the potential naming conflict, but couldn't imagine any use cases that would call for an action such as this. 

Seeing as there are several people requiring an ability to specify a custom mount node, I decided to reuse the `container` prop for the same purpose as being seen in [`React.createPortal`](https://reactjs.org/docs/portals.html) and [MUI](https://material-ui.com/api/popper/#props).

To be able to specify a custom container component for modal nodes, as being seen in [Animated Modals](https://github.com/mpontus/react-modal-hook#animated-modals) example, from now on `rootComponent` prop should be used instead.

This is a breaking change that calls for a major version bump. Please upgrade to `react-modal-hook@3.0.0` to take advantage of the new functionality.
