### ISSUE TITLE
Passing props to modal dialog 

### ISSUE THREAD

**Issue by tgochenour** [mpontus/react-modal-hook#2]
The 'Usage' example given with this hook presents a single static button that invokes a modal component rendered as a static &lt;div/>.

My usecase requires dynamic properties passed to the modal dialog.  The showDialog() function doesn't take custom properties so instead I pass properties through an accessor function before calling showDialog().  Included in this list of properties is the hideDialog() function created by useModal() so the dialog can close itself.  I'm concerned this technique violates proper functional programming since it mutates global state before invoking the dialog's render function.  Is there a better solution?  I think a good enhancement would be that showDialog(props) invokes MyDialog(props) (somehow including how to hide the modal) and then the global state is no longer required.

MyPage.js
```
import { useModal } from "react-modal-hook";
import MyDialog, {setMyDialogProps} from './MyDialog';

function MyPage(props) {
const [showDialog, hideDialog] = useModal(() => MyDialog());
return (
         <button onClick={(evt)=>{_onMyClick(showDialog,hideDialog)}} />
);
}

function _onMyClick(showDialog,hideDialog) {
setMyDialogProps({key:'somekey',hideDialog:hideDialog});
showDialog();
}
```

MyDialog.js
```
let props = {};
export function setMyDialogProps(newprops) {
	props = newprops;
}

export default function MyDialog() {
	return (
		<div role="dialog" className="modal">
			<div className="modal-content">
			<p>Modal content</p>
			<button onClick={props.hideDialog}>Hide modal</button>
			</div>
		</div>
	);
}
```

**Comment by tgochenour** [comment]
I've done some additional research and found The[ react-modal-hook demo](https://codesandbox.io/s/v8qy4w1j77) CodeSandbox.

In it I see the PersonListContainer defining the modal hook like this:
```
  const [showCreateModal, hideCreateModal] = useModal(
    ({ in: open, onExited }) => (
      <PersonFormContainer
        open={open}
        onExited={onExited}
        onClose={hideCreateModal}
      />
    )
  );
```
and PersonFormContainer is declared like this:
```
const PersonFormContainer = ({
  id,
  person,
  createPerson,
  updatePerson,
  onClose,
  ...rest
}) => {...}
```
So I think this example answers my question.  Need to play with this a bit.

**Comment by mpontus** [comment]
Hello, @tgochenour!

`showModal` and `hideModal` do not accept parameters, however it is possible to use external state in modals as shown in [Updating Modals](https://github.com/mpontus/react-modal-hook#updating-modals) example to change modal content when opening it.

Check out this example: https://codesandbox.io/s/y0jp16kx3x

`App.js` shows the simple technique, `App2.js` works the same, but extracts Row into separate component to avoid creating callback on the fly.

If you are using this pattern often, you can probably extend `useModal` with your own hook, as shown in the `App3.js`:

```js
const useModalWithData = modalFactory => {
  const [modalData, setModalData] = useState(undefined);
  const modalComponent = useMemo(() => modalFactory(modalData), [modalData]);
  const [_showModal, hideModal] = useModal(modalComponent, [modalData]);

  const showModal = useCallback(data => {
    setModalData(data);
    _showModal();
  });

  return [showModal, hideModal];
};

const App = () => {
  const [showModal, hideModal] = useModalWithData((data = null) =>
    // v- This is the same function you'd pass to useModal
    () => (
      <ReactModal isOpen>
        <p>Hello, {data.name}</p>
        <button onClick={hideModal}>Hide modal</button>
      </ReactModal>
    )
  );

  return (
    <ul>
      {data.map(datum => (
        <li>
          <button onClick={() => showModal(datum)}>Greet {datum.name}</button>
        </li>
      ))}
    </ul>
  );
};
```

<hr>

As you already noticed from Material-UI example, Redux makes this process easier by allowing you to define modals as part of connected component for every row / cell / etc.

Thanks for the feedback, I will consider adding this to the documentation.

**Comment by gsouf** [comment]
@mpontus In my opinion, not being able to give parameters when calling showModal makes the library harder to use as we have to implement more custom stuff.

Any reasons we could not give parameters that would be passed when the modal is invoked?

example:

```
const [showModal, hideModal] = useModal(({data}) => {
  return <SomeModal something={data.something}/>
});

// ...

// for example when rendered in a list of element when clicking a button for an item.
something.map(item => { 
  <Button key={item.id} onClick={() => {
      showModal({
        something: item
      })
  }}/>
});
```

**Comment by mpontus** [comment]
@gsouf Thanks for your input.

Modal function arguments are reserved for the props injected by a custom root component. See [Animated Modals](https://github.com/mpontus/react-modal-hook#animated-modals) for an example.

My aim for this library is to keep the surface area of the API as small as possible while supporting all sorts of use cases through user-space abstractions. 

I see a few common use cases emerging, namely being able to pass params to modals and [tracking the open state](https://github.com/mpontus/react-modal-hook/pull/24#issuecomment-594592279). I realize how frustrating it can be to require similar functionality, especially if usage patterns repeat themselves across multiple projects. At the same time, I can't discard the merits of just keeping the bare minimum of functionality in the library. I apologize, but I can't convince myself to introduce helpers in the distribution.

**Comment by gsouf** [comment]
@mpontus ok I can understand that.

If it could help anyone... My easy workaround for now is just to create a new "item" component that is rendered in my loop that itself contains a reference to the use modal.

example derived from my example above:

```jsx
function MyItemComponent({item}) {
  const [showModal, hideModal] = useModal(() => {
    return <SomeModal something={item}/>
  });

  return <Button key={item.id} onClick={() => {
      showModal({
        something: item
      })
  }}/>;
}
// ...

something.map(item => { 
  <MyItemComponent item={item}/>
});
```

does not involve introducing some custom hook and I think it still scales properly as long as we handle a proper structure in our project.

**Comment by gsouf** [comment]
@mpontus 

I'm having many issues with not being able to pass params to the fuction.

Basically even with the solution I outlined in the previous comment, it looks like the references passed to the function are not refreshed when the component re-rerenders. 

Still no plans in supporting custom args at call time?

**Comment by mpontus** [comment]
@gsouf You need to pass a second argument to `useModal` functions that specifies all captured variables which when changed would result in a modal re-render. Please see [Updating Modals](https://github.com/mpontus/react-modal-hook#updating-modals) section for an example.

**Comment by SophaDev** [comment]
![berry](https://user-images.githubusercontent.com/69494849/91550176-54f2a680-e952-11ea-8053-24d062771404.jpg)
