### ISSUE TITLE
Only one modal at time

### ISSUE THREAD

**Issue by NicoCaballero** [mpontus/react-modal-hook#20]
Hi, it's possible maintain one open modal at time ?

How can I do it ? Or which is the best approach to do it ?

Thanks

**Comment by mpontus** [comment]
The easiest way to accomplish this is to provide custom component to
`ModalProvider#rootComponent` prop that only renders the last child. Let
me know if that works for you.

**Comment by NicoCaballero** [comment]
I solved it doing that.

Thanks very much!
