### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by saschametz** [mpontus/react-modal-hook#21]
First of all thanks for the great library. I really like this approach to handle modals.

I've just noticed that the demo is broken but it's fixed with a little change.

Old:
```
<ModalProvider container={TransitionGroup}>
```

New:
```
<ModalProvider rootComponent={TransitionGroup}>
```

[Fixed CodeSandbox](https://codesandbox.io/s/react-modal-hook-demo-7qezf)

**Comment by mpontus** [comment]
Thank you! I updated the demo.
