### ISSUE TITLE
useModal show/hide causes parent component's fields to render twice

### ISSUE THREAD

**Issue by tgochenour** [mpontus/react-modal-hook#3]
I have my first modal dialog implemented.  What I find is when I showDialog() the fields/buttons of the parent component (WebForm) will render twice before the dialog appears.  When I hideDialog() the fields/buttons of the parent component again render twice after the dialog disappears.  These renderings are unnecessary as nothing has changed in the parent component.  Tracing why these renderings fire is difficult as React invokes them asynchronously as units of work. There is no stacktrace showing who is responsible.  

Is there something about useModal that invalidates the parent component like a call to setState on a  useState hook?

Here is a simplified version of the parent component using the modal dialog:

```
import React from 'react';
import { useModal } from "react-modal-hook";
import Form from './Form';
import Form from './Field';
import Form from './Button';
import FindDialog from './FindDialog';

let dialogprops = {};
function setDialogProps(props) {
    dialogprops = props;
}

export default function WebForm(props) {
const [showDialog, hideDialog] = useModal(() => FindDialog(dialogprops));
return (
   <Form>
      <Field label="A Field" id="field1"/>
       ...
      <Button source="/img/add.png" hovertext="Add a record" 
            onClick={(context)=>{ 
               setDialogProps({
		hideDialog:hideDialog,
		title:"Find a Record",
		onSelect: (selection) => { console.log('Selected:'+selection); }
	       });
	       showDialog();
            }}
      />
   </Form>
)
```
The Field component uses several hooks of its own.  It is the last console log displaying '*** Field.render' that I see twice.  Here is a simplified version of the Field component:

```
import React, { useState, useEffect, useContext } from 'react';

export default function Field(props) {
	const data = useContext(DataContext);
	let [update, setUpdate] = useState(0);
	function render() {
		console.log('   ***   Field.setUpdate()'); 
		setUpdate((update+1) % Number.MAX_SAFE_INTEGER);
	}
	let [value, setValue] = useState(data?data.fn.getValue(props):'');
	useEffect(() => {
		if(data) {
			let val = data.fn.getValue(props);
			if(value !== val) { 
				console.log('   ***   Field.useEffect:'+props.id+":"+val);
				setValue(val); 
			}
		}
		if(!data && value) {
			console.log('   ***   Field.useEffect:'+props.id+':null');
			setValue('');
		};
	},[data]);

	console.log('   ***   Field.render: '+props.id+' = "'+value+'"  label:'+props.label);
        return ( <div>{props.label}: <input id={props.id} value={value} .../></div> );
}
```

**Comment by tgochenour** [comment]
Upgraded to 1.0.3.  It went from **two** renders to one render on invocation of showDialog()/hideDialog().  Something else in my setup is still invalidating the parent component when the dialog switches on/off.  I wonder what it is...

**Comment by mpontus** [comment]
@tgochenour 

This behavior is expected. `useModal` maintains its own state which, when changed through `showModal/hideModal`, causes an update to the consumer component.

**Comment by tgochenour** [comment]
Not what I would have expected.  From the documentation, React "Portals provide a first-class way to render children into a DOM node that exists outside the DOM hierarchy of the parent component."  A modal component is  independent of the consumer that invokes it.  It should not trigger a rendering of the consumer just because it appears or disappears.  Only if a callback to the consumer updates its state (like in my case a call to onSelect()) should a render of the component be triggered.

So then what is the workaround?  I have the provider wrapping the app:

ReactDOM.render(
	<ModalProvider>
		<App />
	</ModalProvider>
	, document.getElementById('root')
);

...and I have the useModal consumer in my parent component.  Is there a re-arrangement of these to isolate the consumer in an empty component so what is rendered is a no-op?

**Comment by tgochenour** [comment]
The <Button/> component in my example serves as the controller to invoke the dialog with a call to showDialog().  Perhaps this is where I can bury the consumer so only the button is re-rendered.

Something where the dialogprops and hide/show functions are encapsulated within the button and hidden from the parent component:

<```
DialogButton src="/img/add.png" hovertext="Add a record">
   <FindDialog 
        title:"Find a Record",
        onSelect: (selection) => { console.log('Selected:'+selection); }
    />
</DialogButton

```
This would be more declarative.

**Comment by mpontus** [comment]
You are storing the modal state in consumer component. It's not much different from how modals used to be controlled before hooks:

https://reactstrap.github.io/components/modals/

In the case of `react-modal-hook` this state is just hidden behind `useModal`.

Can you measure the effect this update has on your app performance?

**Comment by tgochenour** [comment]
"Can you measure the effect this update has on your app performance?"

I don't have accurate measurements.  When it was rendering twice there was a two/three beat pause before the dialog appeared.  After updating to the 1.0.3 version I found the dialog appearing in one beat as the contents of the parent component would rendered only once.  Now it feels instantaneous.  
There is no lag now that the useModal consumer is hidden inside a button and it is the only component to re-render leaving the rest of the page alone.

Bonus benefit: the dialog reference is now declarative.  All my funny business passing props to the dialog has changed to standard GSX props.  There is a `<DialogButton/>` with the `<FindDialog/>` component (the contents of the Modal) nested within.  The implementation of the modal consumer is hidden inside the button and it is the only thing to re-render when the dialog appears/disappears.

The implementation of the parent component is made way simpler to read compared to the version at the top of this thread.

```
import React from 'react';
import Form from './Form';
import Field from './Field';
import DialogButton from './DialogButton';
import FindDialog from './FindDialog';

export default function WebForm(props) {
return (
   <Form>
      <Field label="A Field" id="field1"/>
       ...
      <DialogButton source="/img/add.png" hovertext="Add a record">
           <FindDialog title:"Find a Record",
                onSelect: (selection) => { console.log('Selected:'+selection); }
          />
      </DialogButton>
   </Form>
)
}
```
