### ISSUE TITLE
Can't resolve 'react-modal

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [mpontus/react-modal-hook#37]
Hi !

Using React-modal-hook for the first time (and using yarn).
Every time I have this issue in my terminal. Can I get some help ? :)

```
./src/Components/Form.js
Module not found: Can't resolve 'react-modal' in '/Users/marine/Test technique/tictactrip/src/Components'
```

**Comment by mpontus** [comment]
Hi, can you please publish your repo so I can try to reproduce the issue?

**Comment by Garrus2142** [comment]
You must install "react-modal" with `yarn add react-modal`
