### ISSUE TITLE
Cannot render modals in container

### ISSUE THREAD

**Issue by seleckis** [mpontus/react-modal-hook#38]
Please check this example. I'm trying to render modals in a div, but they still are rendered in body. There is a `container` prop which seems accept html element (there is no info in docs about it). I provide `ref.current` but seems it doesn't work.

https://codesandbox.io/s/react-modal-hook-demo-forked-nou76?file=/src/index.js

**Comment by mpontus** [comment]
Sorry about the delay. The sandbox appears now to be broken.

![image](https://user-images.githubusercontent.com/2014259/180451067-46eb9683-62e2-4822-a264-19be46d59d86.png)

If you are still having problems, feel free to re-open the issue and I will try to help.
