### ISSUE TITLE
Updating Peer Dependencies

### ISSUE THREAD

**Issue by picosam** [mpontus/react-modal-hook#39]
Hello, is it please possible to update peer dependencies especially to React?
I can create a pull request if you wish!

**Comment by liho00** [comment]
look like this packages stop updating & accepting any pull request, i forked this project & removed the peer dependencies and published to npm https://www.npmjs.com/package/@liholiho/react-modal-hook
npm i @liholiho/react-modal-hook, also reduced bundled size with upgraded react & react-dom version to latest v17.0.2

**Comment by picosam** [comment]
> look like this packages stop updating & accepting any pull request, i forked this project & removed the peer dependencies and published to npm https://www.npmjs.com/package/@liholiho/react-modal-hook npm i @liholiho/react-modal-hook, also reduced bundled size with upgraded react & react-dom version to latest v17.0.2

Thank you! I've actually moved to https://github.com/eBay/nice-modal-react since 😄
