### ISSUE TITLE
Early closure binding calling fn in useModal(fn) was unexpected twist

### ISSUE THREAD

**Issue by tgochenour** [mpontus/react-modal-hook#4]
I believe it is standard behavior of React Hooks for components to render once before the data is retrieved asynchronously and then again a second time once the data response is processed as an effect.

In using the useModal(myFn) hook, I was expecting the call to showDialog() to execute my function with late closure binding from the second rendering and found that the call was instead bound to the closure of the first render.  In the first render the data = useContext(DataContext) is null and in the second render data is an object.  In the call to showDialog() the closure for data is null.  

To insure my dialog is invoked with a reference to the data, I came up with a kludge workaround to pass the data state reference to my function via the global variable window.dialogButtonContext.  There likely is a better way to accomplish this.  Is there?

```
export function DialogButton(props) {
	const data = useContext(DataContext);
	const [showDialog, hideDialog] = useModal( () => {
		const newprops = {hideDialog:hideDialog, data:window.dialogButtonContext};
		window.dialogButtonContext = null;
		return React.cloneElement(children[0], newprops);
	});
	return (
		<button type="button" 
			onClick={evt => { 
				console.log('   ***   DialogButton.onClick:'+(props.label || props.hovertext));
				evt.stopPropagation();
				window.dialogButtonContext = data;
				showDialog(); 
			}}
		>My Button</button>
)}
```

**Comment by mpontus** [comment]
Try passing `[data]` as the second argument to `useModal`.

See this example: https://github.com/mpontus/react-modal-hook#updating-modals

**Comment by mpontus** [comment]
Did not mean to close it. Let me know if it solves your problem.

**Comment by tgochenour** [comment]
Yes, sending [data] as second argument to useModal works.   

I know I read the example documentation you referenced when I first started with react-modal-hook but clearly the second point of this information on updating modals wasn't fully grokked.  The third point, animation, I haven't even tried to contemplate.  I'm just happy my dialog appears when the button is pushed.  Thanks for the help.
