### ISSUE TITLE
Why typescript?

### ISSUE THREAD

**Issue by yairEO** [mpontus/react-modal-hook#7]
I do not know Typescript and do not understand anything in the code, regardless of my 15 years of coding in Javascript :/

Your component seems very ordered and well written, and I would love cloning it and playing with it, but I simply do not understand anything that's going on, and do not wish to learn a new language just to play with a small component :/

Is it possible to re-write it in javascript so it will be accessible to a much wider range of client-side programmers? I would really love that 

I do realize it is a lot to ask but regardless, I hope you understand the frustration at not being able to understand code..at all.

Thanks!

**Comment by mpontus** [comment]
You are right, there is no good reason for why this library could not be written in plain javascript. I don't know when I get to it, but I have this on my list.

**Comment by yairEO** [comment]
Thanks :)have a great week!

**Comment by rhyek** [comment]
Rewriting this in JS sounds like a waste of time to me. Kudos for having written it in TS. JS libraries usually have type definitions on top of the JS code in `.d.ts` files, but you've essentially skipped that and saved yourself from some extra maintenance.

**Comment by mpontus** [comment]
Yeah, on a second thought I don't really think it will be worth the effort. I will be looking for the opportunities to improve the documentation though. Thanks for the feedback!
